org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
kotlin.code.style=official
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
ksp.incremental=true
